### ISSUE TITLE
npm install error - .yalc/vue-images-manager

### ISSUE THREAD

**Issue by juliocesarbr** [iliyaZelenko/laravel-nuxt#2]
Good morning, thanks for this and all your effort. I have this issue making **npm install** and this is that error i have. If a look in the repo i dont see any folder or files like that. I run in in a Linux Debian.

2189 verbose stack Error: ENOENT: no such file or directory, open '/var/www/html/laravel-nuxt-master/.yalc/vue-images-manager/package.json'
2190 verbose cwd /var/www/html/laravel-nuxt-master
2191 verbose Linux 4.15.0-50-generic
2192 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
2193 verbose node v12.2.0
2194 verbose npm  v6.9.0
2195 error code ENOLOCAL
2196 error Could not install from ".yalc/vue-images-manager" as it does not contain a package.json file.
2197 verbose exit [ 1, true ]

**Comment by iliyaZelenko** [comment]
Hi, just remove `vue-images-manager` from dependencies. This is my local package which I developed.
